#!/usr/bin/env python3
"""Collect the evidence behind the reported numbers into one directory.

    uv run python scripts/build_evidence_pack.py

Writes ``thesis_package/evidence/``: the machine-readable result files, the
per-consumer feature frame, the three figures whose provenance is asked about
most often, and two listings that are **generated by calling the code** rather
than transcribed — the column sets and every ``ItalyModel(...)`` construction in
the repository. A hand-typed column list in a thesis appendix goes stale the
first time someone edits ``features.py``; a generated one cannot.

Run this AFTER ``build_thesis_package.py``. That script's ``--clean`` deletes
anything it did not create, which includes this directory — the same trap that
already applies to ``RESULTS_validation.md`` and ``ODD_protocol.html``.
"""
from __future__ import annotations

import ast
import json
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

PKG = ROOT / "thesis_package"
OUT = PKG / "evidence"

# Figures whose population differs from the pinned configuration, and which the
# text therefore has to caveat. Provenance is stated in run_configurations.md.
FIGURES = [
    "f02_spend_mix_vs_paper", "f04_payday_spike",
    "f09_debt_stock_by_subtype", "f10_balance_by_subtype", "f12_still_in_debt",
]

SKIP_DIRS = {".venv", ".git", "abandoned", "italy_further_work", "__pycache__",
             ".ruff_cache", ".pytest_cache", "node_modules", "thesis_package"}


# --------------------------------------------------------------------------- #
# Generated listing 1 — the column sets, by calling the code
# --------------------------------------------------------------------------- #
def feature_sets(features_csv: Path) -> str:
    import pandas as pd

    from synthitaly import diagnostics as D
    from synthitaly import features as F
    from synthitaly import panel as P

    frame = pd.read_csv(features_csv)
    fair = list(F.fair_columns(frame))
    leak = list(F.leak_columns(frame))
    saver_fair = list(F.saver_fair_columns(frame))
    factorable = list(D.factorable_columns(frame[fair]))
    built = [c for c in frame.columns if c != "consumer_id"]
    degenerate = [c for c in built if c not in fair and c not in leak]

    def block(name, cols, note):
        body = "\n".join(f"{i:>3}. `{c}`" for i, c in enumerate(cols, 1))
        return f"\n## {name} — {len(cols)} columns\n\n{note}\n\n{body}\n"

    lines = [
        "# Feature and variable sets",
        "",
        "Generated by calling `synthitaly.features`, `synthitaly.diagnostics` and",
        "`synthitaly.panel` against `features.csv` (800 consumers x 720 days, seed",
        "42). Nothing here is transcribed, so it cannot drift from the code.",
        "Regenerate with `scripts/build_evidence_pack.py`.",
        "",
        "| Set | Used for | n |",
        "|---|---|---:|",
        f"| built frame | everything `build_features()` emits | {len(built)} |",
        f"| degenerate | dropped: zero variance | {len(degenerate)} |",
        f"| **fair** | debtor + climber prediction, debtor clustering | **{len(fair)}** |",
        f"| **naive** | the control condition for every label | **{len(fair) + len(leak)}** |",
        f"| **saver-fair** | saver prediction and clustering | **{len(saver_fair)}** |",
        f"| **factorable** | Study 0 headline (KMO / Bartlett / eigenvalues) | **{len(factorable)}** |",
        "",
        "There is no separate climber set: `is_climber` reuses fair and naive on the",
        "debtor subpopulation. There is no separate saver naive set either — it is",
        "the same 44 columns.",
        "",
        "---",
        block("fair", fair,
              "`features.fair_columns()` — not `LEAK_`-prefixed and not degenerate."),
        block("LEAK_ (naive = fair + these)", leak,
              "Columns that encode a debtor label by construction, not by behaviour."),
        block("saver-fair", saver_fair,
              "`features.saver_fair_columns()` — fair minus `LEAK_SAVER = "
              "('cur_total_out', 'cur_balance')`. Those two carry the month-close "
              "sweep, a debit on the current account that only savers ever have."),
        block("factorable (Study 0 headline)", factorable,
              "`diagnostics.factorable_columns()` — fair minus the compositional "
              "`share_*` block and five reconstructible aggregates. Structural "
              "drops only, verifiable from the frame rather than tuned."),
        block("degenerate (dropped from fair)", degenerate,
              "Zero variance at this configuration, so it cannot enter a "
              "correlation matrix at all."),
        "",
        "---",
        "",
        "## Panel sets used by the paper replications",
        "",
        "A different column vocabulary, built by `synthitaly.panel` and derived",
        "rather than hand-listed (`panel.py:406`).",
        "",
        "| Set | Rule | n |",
        "|---|---|---:|",
        "| **A** (unrestricted) | every predictor column | 50 |",
        "| **B** (fair) | A minus the ten `LEAK_` columns | 40 |",
        "| **C** (behavioural) | B minus `ARREARS_STATE` | 33 |",
        "",
        "Set C is the one used for the Butaru cross-seed horse race; A and B appear",
        "only in the primary-seed two-quarter comparison.",
        "",
        "`ARREARS_STATE` is exactly:",
        "",
        *[f"{i:>3}. `{c}`" for i, c in enumerate(P.ARREARS_STATE, 1)],
        "",
        "Excluded from every panel set as keys or labels:",
        "",
        *[f"  - `{c}`" for c in P._NON_FEATURE],
        "  - anything matching `y_*` or `horizon_complete_*`",
    ]
    return "\n".join(lines)


# --------------------------------------------------------------------------- #
# Generated listing 2 — every model construction, by parsing the AST
# --------------------------------------------------------------------------- #
def run_configurations() -> str:
    rows: list[tuple[str, dict]] = []

    def scan(path: Path, src: str, label: str = "") -> None:
        try:
            tree = ast.parse(src)
        except SyntaxError:
            return
        for node in ast.walk(tree):
            if not isinstance(node, ast.Call):
                continue
            name = getattr(node.func, "id", None) or getattr(node.func, "attr", None)
            if name != "ItalyModel":
                continue
            kw = {}
            for k in node.keywords:
                try:
                    kw[k.arg] = ast.unparse(k.value)
                except Exception:
                    kw[k.arg] = "?"
            rows.append((f"{path.relative_to(ROOT)}{label}:{node.lineno}", kw))

    for p in sorted(ROOT.rglob("*.py")):
        if any(s in p.parts for s in SKIP_DIRS):
            continue
        scan(p, p.read_text(encoding="utf-8", errors="replace"))
    for p in sorted(ROOT.rglob("*.ipynb")):
        if any(s in p.parts for s in SKIP_DIRS):
            continue
        nb = json.loads(p.read_text(encoding="utf-8"))
        for i, cell in enumerate(nb.get("cells", [])):
            if cell.get("cell_type") == "code":
                scan(p, "".join(cell["source"]), label=f" [cell {i}]")

    lines = [
        "# Run configurations",
        "",
        "Every `ItalyModel(...)` construction in the repository, found by parsing",
        "the AST of every `.py` and `.ipynb` outside `.venv/`, `thesis_package/`",
        "and the parked directions. Generated, not transcribed.",
        "",
        "The pinned configuration behind every reported statistic is **800",
        "consumers x 720 days, seed 42, 3 merchants per category per area**",
        "(`scripts/validation_report.py:40`). The simulation start date is **1",
        "January 2017** (`src/synthitaly/model.py:733`) — a constructor keyword",
        "that no caller anywhere in the repo overrides.",
        "",
        "## What produces what",
        "",
        "| Artefact | Configuration |",
        "|---|---|",
        "| Validation report, internal studies 0/A/B/C/D | 800 x 720, seed 42 |",
        "| Data appendix (ledger counts, schemas) | 800 x 720, seed 42 |",
        "| Notebooks `clustering.ipynb`, `prediction.ipynb` | 800 x 720, seed 42 |",
        "| So et al.; Khandani 3m and 6m horizons | 800 x 720, seed 42 |",
        "| Khandani 12m horizon; Butaru, all horizons | 800 x **1,440**, seeds 42-47 |",
        "| **Figures f01-f19** | **800 x 720**, seed 42 |",
        "| Behavioural sensitivity sweep | 300 x 150 (720 for debt), seed 42 |",
        "",
        "**Every figure is now produced at the pinned 800 x 720 configuration** — the same",
        "one every reported statistic comes from. `generate_figures.py` builds one model and",
        "draws all nineteen from it; f01, f04, f05 and f07 show its first 120 days, which is",
        "byte-identical to a 120-day run at the same seed (verified for both the transaction",
        "log and the datacollector frame). Until 22 Aug 2026 the figures came from three",
        "separate runs at 150 x 120, 150 x 720 and 600 x 720, and none could be quoted",
        "alongside the numbers.",
        "",
        "The 1,440-day runs exist because a 9- or 12-month forecast horizon has no evaluable",
        "origination month on a 720-day run (`scripts/_papers.py:111-116`).",
        "",
        "## Every construction",
        "",
        "| Where | consumers | days | seed | merchants/cat |",
        "|---|---:|---:|---:|---:|",
    ]
    for where, kw in rows:
        lines.append(
            f"| `{where}` | {kw.get('n_consumers', '—')} | {kw.get('n_days', '—')} "
            f"| {kw.get('seed', '—')} | {kw.get('n_merchants_per_category', '3 (default)')} |")
    return "\n".join(lines)


def readme(n_rows: int, n_cols: int) -> str:
    """The pack's own index.

    Generated rather than hand-written, and for a specific reason: this file used
    to be a loose .md sitting in ``thesis_package/evidence/``, which
    ``build_thesis_package.py --clean`` deletes on every rebuild because it did not
    create it. It was lost exactly that way once. Anything that has to survive a
    rebuild has to be produced by a script.
    """
    return f"""# Evidence pack

Everything behind the answers to the twelve methodology points, so each one is
checkable rather than trusted.

Rebuild with `uv run python scripts/build_evidence_pack.py` — run it **after**
`build_thesis_package.py`, whose `--clean` deletes anything it did not create.

## Machine-readable results — the source of truth

| File | What it pins |
|---|---|
| `validation_report.json` | The 21 pinned checks, all PASS. Config, label counts, factorability, eigenvalues, clustering, prediction, the saver leak audit. |
| `validation_report.md` | The same numbers as prose. |
| `replicate_so.json` | So et al. — 10 cascade runs, DeLong tests, per-fold Ginis, IV maps. |
| `replicate_khandani.json` | Khandani et al. — 18 result keys, stratification lifts, the straight-roller block, CART importances. |
| `replicate_butaru.json` | Butaru et al. — 6 seeds x 3 horizons x 3 models, cross-seed spread, threshold and overfitting sweeps. |
| `features.csv` | The per-consumer feature frame: {n_rows} rows x {n_cols} columns. |

## Generated listings — never transcribed by hand

| File | How it is produced |
|---|---|
| `feature_sets.md` | Calls `fair_columns()`, `leak_columns()`, `saver_fair_columns()` and `factorable_columns()` on `features.csv`, plus the panel set rules. Cannot drift from the code. |
| `run_configurations.md` | Parses the AST of every `.py` and `.ipynb` in the repo and lists every `ItalyModel(...)` with file:line and kwargs. |
| `README.md` | This file, from `build_evidence_pack.py`. |

## Figures

`f02` (spending calibration), `f04` (payday spike), `f09` / `f10` / `f12` (debt
trajectories), as 300 dpi PNG and vector PDF.

All five come from the pinned **800 x 720, seed 42** configuration — the same one
every reported statistic uses. `f04` shows its first 120 days, which the seeding
makes byte-identical to a 120-day run. See `run_configurations.md`.

Note what each one plots: `f02` and `f04` are **euro**, not transaction counts;
`f09` is a **total** across the subtype; `f10` is a **mean** within it; `f12` is a
**count** of households.

## Three corrections worth knowing about before quoting anything

These were all open questions in the previous version of this pack. All three are
now fixed, and the fixes moved published numbers.

1. **`CATEGORY_SHARES` are euro shares and were used as selection probabilities.**
   The paper's Figure 4 (§2.1) is titled *Average shares of expenditure categories*
   and Figure 6 benchmarks it against COICOP national-accounts expenditure — they
   are shares of euros. `sample_category()` used them directly as the probability of
   picking a category, then drew the ticket independently, so the model matched the
   paper in transaction **counts** and missed on euros: travel took 19.8% of euros
   against the paper's 9.0%. Selection is now `p ∝ share / E[ticket]`; the residual
   error on a real run is 0.6pp, all sampling noise. **This changed every
   transaction in the model**, so every number in this pack moved with it. The
   attribution block above `EXPECTED` in `scripts/validation_report.py` names the
   cause of each moved row.

2. **`replicate_so.json` was not reproducible across processes.** The script seeded
   each cascade with `hash(key) % 1000`, and Python salts string hashing per
   process. Over four runs the six late-fee DeLong comparisons were stable but the
   four 90-DPD ones flipped verdict in three runs of ten. The seed is now
   `blake2b(key)` (`replicate_so.py:_stable_seed`), verified identical across fresh
   interpreters. Combined with the units fix, **eight of ten comparisons now reject,
   not six**; `docs/RESULTS_validation.md` §7.1 carries the full table and records
   both earlier counts.

3. **Kappa and F used a threshold chosen on the test labels.** Khandani and Butaru
   called `classification_scores` without a threshold, so it took the ROC tangency
   point of the scores being evaluated. Both now take it from the training fold.
   AUC is threshold-free and did not move; kappa and F did, most visibly for the
   ridge logit on Butaru's behavioural-only set C (kappa 0.501 -> 0.395), which had
   been benefiting the most.

## Regenerating the numbers themselves

```bash
uv run python scripts/validation_report.py      # the 21 pinned checks, ~30s
uv run pytest -m slow                           # the loose regression floors
uv run python scripts/replicate_so.py           # ~2 min, reproducible
```
"""


def main() -> int:
    if not PKG.exists():
        print(f"! {PKG} does not exist — run build_thesis_package.py first")
        return 1
    OUT.mkdir(parents=True, exist_ok=True)

    copied, missing = 0, []
    for rel in ["data/validation_report.json", "data/replicate_so.json",
                "data/replicate_khandani.json", "data/replicate_butaru.json",
                "data/features.csv", "reports/validation_report.md"]:
        src = PKG / rel
        if src.exists():
            shutil.copy2(src, OUT / src.name)
            copied += 1
        else:
            missing.append(rel)
    for stem in FIGURES:
        for ext in ("png", "pdf"):
            src = PKG / "figures" / f"{stem}.{ext}"
            if src.exists():
                shutil.copy2(src, OUT / src.name)
                copied += 1
            else:
                missing.append(f"figures/{stem}.{ext}")

    (OUT / "feature_sets.md").write_text(
        feature_sets(OUT / "features.csv"), encoding="utf-8")
    (OUT / "run_configurations.md").write_text(run_configurations(), encoding="utf-8")

    feat = OUT / "features.csv"
    if feat.exists():
        import csv
        with feat.open(newline="", encoding="utf-8") as fh:
            r = csv.reader(fh)
            header = next(r, [])
            n_rows = sum(1 for _ in r)
        (OUT / "README.md").write_text(readme(n_rows, len(header)), encoding="utf-8")
    else:
        missing.append("README.md (needs features.csv for its row/column counts)")

    print(f"  copied {copied} files into {OUT}")
    print("  generated feature_sets.md, run_configurations.md, README.md")
    if missing:
        print(f"  ! missing: {', '.join(missing)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
